# Generated by Django 3.1.6 on 2021-02-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='emoji',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
