# Generated by Django 3.1.6 on 2021-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_auto_20210222_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='emoji',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
