# Generated by Django 3.1.6 on 2021-03-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_auto_20210223_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
    ]
