# Generated by Django 3.1.6 on 2021-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.IntegerField(default=0),
        ),
    ]
